---
name: "Renovate Helm Releases"
description: "Creates Renovate annotations in Flux2 Helm Releases"
inputs:
  cluster-path:
    description: "Path to the folder containing your Flux2 Helm Repositories and Helm Releases"
    required: true
  debug:
    description: "Turn on debug logging"
    required: false
    default: "no"
  dry-run:
    description: "Do not alter Helm Release files"
    required: false
    default: "no"
runs:
  using: "docker"
  image: 'docker://ghcr.io/k8s-at-home/renovate-helm-releases:v1.1.0'
  args:
  - ${{ inputs.cluster-path }}
  - ${{ inputs.debug }}
  - ${{ inputs.dry-run }}
