---
name: Lint and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore: tests

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: "pip install -r requirements.txt"
    - run: "python3 ./test_renovate.py"
