---
name: Lint and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Get k8s-at-home token
      id: get-app-token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ secrets.K8S_AT_HOME_APP_ID }}
        private_key: ${{ secrets.K8S_AT_HOME_APP_PRIVATE_KEY }}
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ steps.get-app-token.outputs.token }}

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore: tests

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get k8s-at-home token
      id: get-app-token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ secrets.K8S_AT_HOME_APP_ID }}
        private_key: ${{ secrets.K8S_AT_HOME_APP_PRIVATE_KEY }}
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ steps.get-app-token.outputs.token }}

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install requirements
      run: "pip install -r requirements.txt"

    - name: Run tests
      run: "python3 ./test_renovate.py"
