name: publish_action

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY_IMAGE: renovate-helm-releases

jobs:
  docker:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push
      # if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        # build-args: VERSION=${{ steps.prep.outputs.version }}
        context: .
        file: ./Dockerfile
        push: false
        tags: |
          ghcr.io/k8s-at-home/${{ env.REGISTRY_IMAGE }}:latest
